# Generated by Django 4.2.3 on 2023-11-05 06:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('username', models.CharField(max_length=200)),
                ('profession', models.CharField(max_length=200)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='img')),
                ('about', models.CharField(max_length=500)),
                ('profile_id', models.UUIDField(default=uuid.UUID('c72f87f8-9984-4397-809d-c535c5a1ff1b'), editable=False, primary_key=True, serialize=False, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
