# Generated by Django 4.2.3 on 2023-11-05 06:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='about',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_id',
            field=models.UUIDField(default=uuid.UUID('8d80a239-0ec7-49ff-9702-ce4d108dfca0'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
