# Generated by Django 4.2.3 on 2023-11-04 17:38

import ckeditor.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0002_category_alter_post_post_id_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_id',
            field=models.UUIDField(default=uuid.UUID('841f4335-e9eb-4607-add3-becc8997e2aa'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='body',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_id',
            field=models.UUIDField(default=uuid.UUID('bbdcd39d-a4b9-42ac-b713-50b9d9b7ad38'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
