# Generated by Django 4.2.3 on 2023-11-05 06:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0004_alter_category_category_id_alter_post_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_id',
            field=models.UUIDField(default=uuid.UUID('bb64d008-43dc-4d33-a127-210c78d7b4fb'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_id',
            field=models.UUIDField(default=uuid.UUID('d4261796-bc03-48b6-b017-096401de996c'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
