# Generated by Django 4.2.3 on 2023-11-05 06:30

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_userprofile_profile_id'),
        ('cmsapp', '0005_alter_category_category_id_alter_post_post_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='writer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiles.userprofile'),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_id',
            field=models.UUIDField(default=uuid.UUID('0ac34286-f6b9-43d9-8b73-8dba47da2f8c'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_id',
            field=models.UUIDField(default=uuid.UUID('e1a261cb-054d-4d7b-a0fd-d78490b88ba1'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
